apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-xffu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-nodevfile-nodocker-rhtap-three-component-scenarios-xffu
    app.kubernetes.io/part-of: mc-three-scenarios
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-xffu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-xffu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-xffu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eeqw-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-xffu@sha256:4e8e53e19448b8c2d87ebfe7e2d82d6a3cc12460c754f8fab3cad5edc61cfc19
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
