apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-fmrz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eeqw-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-fmrz@sha256:b7442fdb9849f36cb8b20241fc7e4f4f126a24a42187f30cbaefe78172b1bc48
        name: my-go
        resources: {}
status: {}
